// docsite-page.mjs — the one HTML shell for docsite pages, and the ONE write path for generated
// pages: bin/docsite-build.mjs and the admin save route both go through renderAndWritePage(), so
// the two writers of pages/<urlPath>/index.html are two callers of one function, never two
// implementations (write-cardinality rule; divergence here is what docsite-parity.test.mjs exists
// to catch).
//
// fact: no clock reaches the output — the page embeds src-sha256, not a timestamp, so two builds
//   of the same source are byte-identical UNCONDITIONALLY / determinism by construction is
//   strictly stronger than determinism under CW_NOW (expiry: never)
// fact: pages carry a tier-4 "Generated by" header in line 2 / docs-doctor and humans both need
//   the never-hand-edit claim in the artifact itself (expiry: never)

import { mkdirSync, readFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { createHash } from 'node:crypto';
import { writeAtomic } from '../monitor/lockfile.mjs';
import { esc } from './render-markdown.mjs';
import { renderDocBody } from './docsite-md.mjs';
import { PAPER_CSS, MARK_IMG, MARK_ICON } from './brand-tokens.mjs';
import { snapshotBeforeWrite } from './docsite-versions.mjs';
// docHref, not a second `/${alias || urlPath}/` here: the canonical URL and the index link must be
// the SAME string or the page declares a canonical the site does not link. docsite-manifest.mjs
// imports nothing that reaches back here, so this is an edge and not a cycle.
import { docHref } from './docsite-manifest.mjs';
import { rootOf } from './docsite-roots.mjs';

export const sha256Hex = (data) => createHash('sha256').update(data).digest('hex');

// Palette: the bond-paper/gold livery from admin/static/panel-light.css + panel.css, carried here
// via lib/brand-tokens.mjs rather than restated — operator ruling 2026-08-29, replacing the
// evaluations/aikido-comparison amber palette this shell used before. `code` is set in --head on
// a --panel2 chip, as lib/md-view.mjs sets it; --sev violet stays reserved for "actively
// exploited" (see brand-tokens.mjs).
//
// Exported so a generator outside the docsite can inline the SAME tokens rather than keep a
// second copy of them. Same reasoning as the write-cardinality rule at the top of this file: a
// pasted duplicate is a fork that nothing measures, and it drifts the first time this palette
// is touched. Importers inline it verbatim — they never edit it.
export const CSS = `
${PAPER_CSS}
*{box-sizing:border-box}
/* ONE KNOB FOR THE WHOLE DOCUMENT. Everything below is expressed in rem/em/ch, so the root
   font-size is the only thing that sets scale — change --doc-scale and the headings, gutters,
   rules, badges and the column all move together instead of drifting apart. That is what makes
   this a grid rather than a pile of tuned numbers: at 1 it is the old 15px page exactly, at 2 it
   is that page at 200%. The measure is held by p{max-width:84ch}, which is in CHARACTERS, so the
   line length a reader actually sees stays constant as the type grows — scaling a column in px
   would have doubled the words per line and made the larger type harder to read, not easier. */
:root{--doc-scale:2}
html{font-size:calc(100% * var(--doc-scale))}
body{margin:0;padding:0 0 5rem;background:var(--bg);color:var(--ink);font:0.9375rem/1.62 var(--sans)}
.wrap{max-width:55rem;margin:0 auto;padding:0 1.5rem}
.skip{position:absolute;left:-9999px}.skip:focus{position:static;display:inline-block;padding:.5rem}
header.site{border-bottom:1px solid var(--line);padding:1.1rem 0;margin-bottom:2.2rem}
header.site .wrap{display:flex;gap:1.2rem;align-items:center;flex-wrap:wrap}
.brand{color:var(--head);font-weight:600;text-decoration:none;display:inline-flex;align-items:center;gap:.31rem}
.brand .seal{width:1.35rem;height:1.35rem;flex:none}
nav.docs a{color:var(--mut);text-decoration:none;margin-right:1rem}
nav.docs a[aria-current="page"]{color:var(--acc)}
nav.docs a:hover{color:var(--ink)}
h1{font-size:1.9rem;line-height:1.2;margin:0 0 .5rem;color:var(--head);letter-spacing:-.015em}
h2{font-size:1.28rem;color:var(--head);margin:2.4rem 0 .35rem;letter-spacing:-.01em}
h3{font-size:1.02rem;color:var(--head);margin:1.8rem 0 .3rem}
h4,h5,h6{color:var(--head);margin:1.4rem 0 .3rem}
p{max-width:84ch}
a{color:var(--acc)}
code{font:.88em var(--mono);background:var(--panel2);padding:.1em .35em;border-radius:3px;color:var(--head)}
pre.cb{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:.9rem 1rem;overflow-x:auto}
pre.cb code{background:none;padding:0}
blockquote{border-left:3px solid var(--line2);margin:1rem 0;padding:.1rem 0 .1rem 1rem;color:var(--mut)}
.tw{overflow-x:auto;margin:1.2rem 0}
table{border-collapse:collapse;width:100%}
th,td{border:1px solid var(--line);padding:.45rem .7rem;text-align:left;vertical-align:top}
th{background:var(--panel2);color:var(--head)}
hr{border:0;border-top:1px solid var(--line);margin:2rem 0}
ul,ol{padding-left:1.4rem}
.callout{background:var(--panel);border:1px solid var(--line2);border-left:3px solid var(--acc);border-radius:6px;padding:.7rem 1rem;margin:1.2rem 0}
figure.svgfig{margin:1.4rem 0;text-align:center}
figure.svgfig img{max-width:100%;background:#fff;border:1px solid var(--line);border-radius:8px;padding:8px}
.badge{display:inline-block;font:600 .6875rem/1 var(--mono);letter-spacing:.06em;padding:.3em .55em;border-radius:4px;border:1px solid var(--line2);color:var(--mut);vertical-align:middle;margin-left:.6rem}
.badge.warn{color:var(--crit);border-color:var(--crit)}
footer.site{border-top:1px solid var(--line);margin-top:3rem;padding-top:1rem}
footer.site .wrap{font:.75rem/1.6 var(--mono);color:var(--dim)}
.doclist{list-style:none;padding:0}
.doclist li{border:1px solid var(--line);background:var(--panel);border-radius:8px;padding:.8rem 1rem;margin:.6rem 0}
.doclist a{color:var(--head);text-decoration:none;font-weight:600}
.doclist .fresh{font:.6875rem/1 var(--mono);margin-left:.6rem}
.fresh.stale{color:var(--crit)}.fresh.unknown{color:var(--mut)}.fresh.fresh{color:var(--ok)}
/* .fresh.fresh is the same class written twice, so it matches EVERY .fresh badge, not only the
   fresh ones — which painted the DRAFT label the success green. A draft wearing the colour that
   means "good and current" is the exact inversion this project bans, so the label rule is declared
   AFTER it and wins on source order at equal specificity. The green stays for real freshness in
   the local drafting view, where it is answering the question it was written for. */
.fresh.label{color:var(--mut);text-transform:uppercase;letter-spacing:.06em;font-weight:600}
sup.ref-cite{font-size:.72em}
sup.ref-cite a{color:var(--acc);text-decoration:none}
sup.ref-cite a:hover{text-decoration:underline}
sup.ref-cite.ref-undefined{color:var(--crit)}
.references{margin-top:2.4rem;padding-top:1.2rem;border-top:1px solid var(--line)}
.references h2{margin-top:0}
.reflist{list-style:none;padding:0;counter-reset:none}
.reflist li{padding:.5rem 0;border-bottom:1px solid var(--line);font-size:.92em}
.reflist li:last-child{border-bottom:0}
.ref-back{color:var(--mut);font:.85em var(--mono);text-decoration:none;margin-right:.4rem}
.ref-back:hover{color:var(--acc)}
.ref-title{color:var(--ink);font-weight:600}
.ref-link{color:var(--acc);text-decoration:none;margin-left:.3rem}
.ref-link:hover{text-decoration:underline}
.ref-desc{margin:.25rem 0 0;color:var(--mut);max-width:74ch}
/* A hint, not a button: the docsite bundle runs under script-src 'self' (see editor/edit.html),
   so an inline onclick would be blocked by CSP and the control would do nothing while looking
   like it worked. The print stylesheet below is the actual feature; the browser's own print
   command drives it, and needs no script at all. */
.pdf{color:var(--dim);font:11px/1 var(--mono);letter-spacing:.04em;margin-left:auto;
  border:1px solid var(--line);border-radius:4px;padding:.35em .6em}

/* Print. The PDF is this stylesheet under @media print — there is no second renderer and no
   headless browser, so what prints is what the page already is (zero runtime dependencies).
   Paper is its own medium: the reader's theme, the chrome and the controls are all screen
   furniture, and a px measure sized for a monitor is wrong on A4. */
@media print{
  :root{--bg:#fff;--panel:#fff;--panel2:#f4f4f2;--ink:#111;--head:#000;--mut:#444;--dim:#555;
        --line:#bbb;--line2:#999}
  body{padding:0;font-size:10.5pt;line-height:1.42}
  .wrap{max-width:none;padding:0}
  header.site,footer.site,nav.docs,.skip,.pdf{display:none!important}
  main{margin:0}
  h1{font-size:19pt;margin:0 0 .4em}h2{font-size:13pt;margin:1.4em 0 .3em}h3{font-size:11pt}
  h1,h2,h3,h4{break-after:avoid;page-break-after:avoid}
  table{font-size:9pt;width:100%}
  thead{display:table-header-group}
  tr,figure.svgfig,.callout,pre.cb{break-inside:avoid;page-break-inside:avoid}
  th,td{padding:.28em .45em}
  a{color:inherit;text-decoration:none}
  a[href^="http"]::after{content:" (" attr(href) ")";font-size:8pt;color:#555;word-break:break-all}
  figure.svgfig img{border:1px solid #ccc}
  .badge{border-color:#999;color:#444}
  @page{margin:16mm 14mm 18mm}
}
`;

const navHtml = (nav = [], currentSlug = '') => nav.length
  ? `<nav class="docs" aria-label="Documents">${nav.map((n) =>
    `<a href="${esc(n.href)}"${n.slug === currentSlug ? ' aria-current="page"' : ''}>${esc(n.title)}</a>`).join('')}</nav>`
  : '';

// THE PUBLIC ORIGIN the generated pages name themselves by. A canonical URL and an og:url are
// ABSOLUTE by specification — a relative canonical is ignored and a relative og:image is not
// fetched by most crawlers — so the origin has to be baked into the bytes. Read at call time, so a
// test or a preview deployment can set it; the committed artifacts carry the default, which is the
// production host the launchlist probes (monitor/private/launchlist/config.json `site`).
export const siteBase = () => (process.env.CW_DOCSITE_BASE_URL || 'https://i.commitwork.online').replace(/\/+$/, '');

// The og:image. 1200x630 is not advice: X and LinkedIn crop anything else, and Slack falls back to
// a small-card layout. Produced by bin/docsite-og-image.mjs into docsite/public/, which
// bin/docsite-publish.mjs passes through to the bundle root — so the tag and the asset ship in one
// act. If the asset is ever removed, the TAG MUST GO WITH IT: an og:image naming a 404 is worse
// than no og:image, because a crawler that fetched it records the failure against the page.
// bin/docsite-publish.mjs refuses to publish when the tag is emitted and the file is absent.
export const OG_IMAGE = '/og.png';

// Head metadata, opt-in. Emitted only for the arguments it is GIVEN, which is what keeps every
// renderShellPage() caller (bin/taxonomy-render.mjs, bin/scanner-taxonomy-render.mjs,
// bin/remediation-web.mjs, bin/taxonomy-web.mjs) byte-identical to before this existed: they pass
// neither, so they get neither. og:* is all-or-nothing on purpose — a partial Open Graph card
// renders worse than none, so the three required tags are emitted together or not at all.
const headMeta = ({ description = '', canonicalPath = '', title = '', noindex = false }) => {
  const out = [];
  if (noindex) out.push('<meta name="robots" content="noindex">');
  if (description) out.push(`<meta name="description" content="${esc(description)}">`);
  const canonical = canonicalPath ? `${siteBase()}${canonicalPath}` : '';
  if (canonical) out.push(`<!-- nosemgrep: html.security.audit.missing-integrity.missing-integrity -- canonical is metadata and is never fetched --><link rel="canonical" href="${esc(canonical)}">`);
  // A page that asks not to be indexed advertises no share card either.
  if (description && canonical && !noindex) {
    out.push('<meta property="og:type" content="website">',
      '<meta property="og:site_name" content="commitwork docs">',
      `<meta property="og:title" content="${esc(title)}">`,
      `<meta property="og:description" content="${esc(description)}">`,
      `<meta property="og:url" content="${esc(canonical)}">`,
      `<meta property="og:image" content="${esc(siteBase() + OG_IMAGE)}">`,
      '<meta property="og:image:width" content="1200">',
      '<meta property="og:image:height" content="630">',
      '<meta name="twitter:card" content="summary_large_image">');
  }
  return out.length ? `\n${out.join('\n')}` : '';
};

// The footer's site links, opt-in for the same reason headMeta is. `mailto:` is the contact path a
// static host can offer without a form, and a form is what would turn this site into something
// that collects data — see docsite/content/privacy.md, which says so because it is true of the
// bundle, not as a posture.
const footerLinks = (links = []) => (links.length
  ? ` · ${links.map((l) => `<a href="${esc(l.href)}">${esc(l.text)}</a>`).join(' · ')}`
  : '');

// Cloudflare's email obfuscation rewrites every mailto on the custom domain and injects a decoder
// <script>, which the privacy page says no page carries. It skips content between these markers.
const EMAIL_OFF = '\n<!--email_off-->';
const EMAIL_ON = '\n<!--/email_off-->';

const shell = ({ title, bodyHtml, srcHash, extraHead = '', nav = [], currentSlug = '', badge = '', generator = 'bin/docsite-build.mjs', description = '', canonicalPath = '', noindex = false, siteLinks = [] }) => `<!doctype html>
<!-- Generated by ${generator} — regenerate, never hand-edit. src-sha256:${srcHash.slice(0, 12)} -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)} — commitwork docs</title>${headMeta({ description, canonicalPath, title, noindex })}
${MARK_ICON}
<style>${CSS}</style>${extraHead}
</head>
<body data-src-sha256="${srcHash}">${siteLinks.length ? EMAIL_OFF : ''}
<a class="skip" href="#main">Skip to content</a>
<header class="site"><div class="wrap"><a class="brand" href="/">${MARK_IMG}commitwork docs</a>${navHtml(nav, currentSlug)}<span class="pdf" aria-hidden="true">⌘P → PDF</span></div></header>
<main id="main"><div class="wrap">
<h1>${esc(title)}${badge}</h1>
${bodyHtml}
</div></main>
<footer class="site"><div class="wrap">commitwork docs · generated from Markdown · src ${esc(srcHash.slice(0, 12))}${footerLinks(siteLinks)}</div></footer>${siteLinks.length ? EMAIL_ON : ''}
</body>
</html>
`;

// A doc page. state !== 'published' renders an honest badge (hidden = reachable-not-listed by
// declaration; draft appears only in local preview since the publish bundle excludes it).
// The shell always renders its own <h1> from the manifest's declared title (the canonical
// identity, independent of whatever the source happens to say). Markdown content routinely
// opens with its own '# Title' line, which renderDocBody turns into a second, leading <h1> —
// measured live on the field guide page: two <h1>s back to back, one from each source. Stripped
// here, once, rather than asking every markdown source to omit its own title — a source that
// still opens with a real H1 (for its own readability as plain markdown, or when rendered
// somewhere other than this shell) keeps it; only the DUPLICATE that would appear on this page
// is dropped.
// THE shell, for the GENERATORS. bin/taxonomy-render.mjs, bin/scanner-taxonomy-render.mjs,
// bin/remediation-web.mjs and bin/taxonomy-web.mjs build their body HTML from JSON rather than
// Markdown, so they cannot go through renderPage() — but before this they each carried a private
// copy of the chrome instead, which is the divergence the write-cardinality rule at the top of
// this file exists to prevent. They are now callers, not implementations.
//
// `extraHead` lands AFTER <style>${CSS}</style>, so a generator's own rules override the shell's
// by ordinary cascade — that is where page-specific table CSS goes, and where a wide page puts its
// `@page{size:A4 landscape}` override. The shell's @media print block is the PDF renderer for
// every page that uses it; a generator overriding page SIZE keeps that renderer rather than
// replacing it, which is what let taxonomy-reference stop being self-styled without losing print.
//
// `generator` names the real producer in the line-2 never-hand-edit header, which docs-doctor and
// human readers both read. It defaults to bin/docsite-build.mjs, so every existing caller renders
// byte-identically to before this export existed.
export function renderShellPage(opts) { return shell(opts); }

const stripLeadingH1 = (html) => html.replace(/^\s*<h1[^>]*>[\s\S]*?<\/h1>\s*/, '');

// THE footer links every docsite page carries. Both are reachable from the bundle: /privacy/ is a
// manifest doc and the mailto needs no server. The contact address is the one LICENSING.md already
// publishes as the licensing contact — not a second address invented for the site, which would be
// an address nobody monitors.
export const SITE_LINKS = Object.freeze([
  Object.freeze({ href: '/privacy/', text: 'Privacy' }),
  Object.freeze({ href: '/licensing/', text: 'Licensing and contact' }),
]);

// A meta description, derived from the source rather than declared in the manifest. Declaring it
// would mean a fourth place to keep current and a page whose description silently predates its
// rewrite; derived, it cannot go stale against the text it summarises. Takes the first real
// paragraph: the manifest's title is already the <h1>, so a leading '# …' line is the duplicate the
// shell strips from the body and is dropped here for the same reason.
// Comments are removed until none remain: one pass over `<!-<!-- x -->- note -->` leaves a whole comment.
// This loop shape is the one CodeQL's incomplete-multi-character-sanitization query recognises.
const stripComments = (s) => { let next; while ((next = s.replace(/<!--[\s\S]*?-->/g, '')) !== s) s = next; return s; };

export function metaDescription(md, limit = 155) {
  const body = stripComments(String(md))
    .replace(/^\uFEFF/, '')
    .split(/\n{2,}/)
    .map((b) => b.trim())
    .find((b) => b && !b.startsWith('#') && !b.startsWith('>') && !b.startsWith('|') && !b.startsWith('```')) || '';
  const flat = body
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')      // links → their text
    .replace(/[*_`]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  if (flat.length <= limit) return flat;
  // Cut on a word boundary. A description sliced mid-word is quoted mid-word in a search result.
  return `${flat.slice(0, flat.lastIndexOf(' ', limit - 1) > 0 ? flat.lastIndexOf(' ', limit - 1) : limit - 1)}…`;
}

export function renderPage({ doc, md, nav = [] }) {
  const srcHash = sha256Hex(md);
  const badge = doc.state === 'published' ? '' : `<span class="badge${doc.state === 'draft' ? ' warn' : ''}">${esc(doc.state)}</span>`;
  // A doc that is not published must not invite indexing of a URL the next publish may withdraw —
  // hidden means reachable-and-unlisted by declaration, and draft never leaves the local preview.
  return shell({
    title: doc.title,
    bodyHtml: stripLeadingH1(renderDocBody(md)),
    srcHash,
    nav,
    currentSlug: doc.slug,
    badge,
    description: metaDescription(md),
    canonicalPath: docHref(doc),
    noindex: doc.state !== 'published',
    siteLinks: SITE_LINKS,
  });
}

// The home page's description and social card text. This is the one string on the site that is not
// derived from a document, so it is the one that can drift from what commitwork is — it names the
// three things the tool does and the thing this site is, and nothing it cannot be held to.
export const INDEX_DESCRIPTION = 'Reference documents for commitwork: a repository security scanner, '
  + 'local CI runner and scheduled monitoring system, with remediation and compliance-evidence tooling.';

// The index. rows: [{title, href, state, freshness}] — freshness is one of fresh|stale|unknown|
// imported and is ALWAYS shown: an unknown renders as unknown, never as fresh (explicit uncertainty)
// and never as an alarm (explicit uncertainty).
export function renderIndex({ rows, note = '', showFreshness = false }) {
  const items = rows.map((r) => {
    // THE FRESHNESS SIGNAL IS OPT-IN, and both callers are deliberate. On the PUBLIC index it is
    // off (operator instruction 2026-08-29): it answers a build question — "is this HTML current
    // with its source" — that a reader cannot act on, and sitting beside the title it read as a
    // claim about the writing. In the panel's LOCAL DRAFTING VIEW it is the entire point, because
    // fresh/stale/unknown is what tells the operator a page needs rebuilding.
    // Defaulting it OFF and passing it explicitly is what makes that a decision each caller makes
    // rather than one the last edit happened to leave behind — the first version of this change
    // hid it everywhere and blinded the drafting view without failing anything.
    const fresh = r.label ? `<span class="fresh label">${esc(r.label)}</span>`
      : showFreshness
        ? (r.freshness === 'imported'
          ? '<span class="fresh unknown">imported snapshot</span>'
          : `<span class="fresh ${esc(r.freshness)}">${esc(r.freshness)}</span>`)
        : '';
    const badge = r.state && r.state !== 'published' ? `<span class="badge">${esc(r.state)}</span>` : '';
    return `<li><a href="${esc(r.href)}">${esc(r.title)}</a>${badge}${fresh}</li>`;
  }).join('\n');
  const bodyHtml = `${note ? `<p>${esc(note)}</p>` : ''}\n<ul class="doclist">\n${items}\n</ul>`;
  return shell({
    title: 'Documents',
    bodyHtml,
    srcHash: sha256Hex(rows.map((r) => `${r.href}\t${r.title}\t${r.state}\t${r.freshness}\t${r.label || ''}`).join('\n')),
    description: INDEX_DESCRIPTION,
    canonicalPath: '/',
    siteLinks: SITE_LINKS,
  });
}

// Cloudflare Pages serves index.html with a 200 for EVERY unmatched URL unless the bundle carries
// a root 404.html — so a hidden or deleted page reads as "still published" to anyone probing it,
// a soft green about content that does not exist. Measured on this project 2026-08-28: /guide/
// answered 200 with the index body after its draft was excluded from the deploy — the same defect
// commitwork-web had already fixed. This page's PRESENCE in the bundle is what flips Pages from
// SPA fallback to real 404s; its content is secondary.
export function render404() {
  const bodyHtml = '<p>No page lives at this address. It may have been unpublished, or never existed.</p>\n'
    + '<p><a href="/">The document index</a> lists everything published.</p>';
  // noindex and NO canonical: a 404 that names a canonical URL asks a crawler to index the address
  // that just failed. The description exists so the page is not a blank card when one is shared.
  return shell({
    title: 'Not found',
    bodyHtml,
    srcHash: sha256Hex('404'),
    description: 'No page lives at this address on the commitwork document site.',
    noindex: true,
    siteLinks: SITE_LINKS,
  });
}

// THE write path for a generated page — every writer of pages/<urlPath>/index.html calls this.
export function renderAndWritePage({ doc, md, outPath, nav = [] }) {
  const html = renderPage({ doc, md, nav });
  let previous = null;
  try { previous = readFileSync(outPath, 'utf8'); } catch { /* first render — nothing to snapshot */ }
  snapshotBeforeWrite(doc.urlPath, 'generated', previous, { root: rootOf(doc) });
  mkdirSync(dirname(outPath), { recursive: true });
  writeAtomic(outPath, html);
  return { html, srcHash: sha256Hex(md) };
}

export { renderDocBody };
