import { test, describe, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { classifyResolution, packageNameOf, parseYarnLock, parsePackageLock, diffProvenance, compareSlices, targetIdentity } from '../dep-provenance.mjs';

afterEach(() => { delete process.env.CW_DEP_PROVENANCE; });

describe('dep-provenance — classifying one resolution', () => {
  test('registry URLs, including a scoped tarball path', () => {
    for (const s of [
      'https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz#35797f1',
      'https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.26.2.tgz#4b5fab9',
      'https://registry.yarnpkg.com/x/-/x-1.0.0.tgz',
      'https://npm.pkg.github.com/@acme/x/-/x-1.0.0.tgz',
    ]) assert.equal(classifyResolution(s), 'registry', s);
  });

  test('git resolutions in every form the lockfiles use', () => {
    for (const s of [
      'git+https://github.com/google/closure-net.git#6f48f578d3e80fe7a85e530a5d95b9351433d135',
      'git+ssh://git@github.com/a/b.git#abc',
      'git://github.com/a/b.git#v1',
      'https://github.com/a/b.git#abc',
      'github:a/b#abc', 'gitlab:a/b', 'bitbucket:a/b',
    ]) assert.equal(classifyResolution(s), 'git', s);
  });

  test('a bare tarball URL is `archive`, not `registry` — pinned to a host, not an identity', () => {
    assert.equal(classifyResolution('https://example.com/dist/thing-1.0.0.tgz'), 'archive');
  });

  test('local paths', () => {
    for (const s of ['file:../pkg', 'link:./local', 'portal:./p']) assert.equal(classifyResolution(s), 'file');
  });

  test('FAILS TOWARD unknown, never toward registry', () => {
    // Reading an unrecognised resolution as registry-backed would silently assert that a registry
    // advisory applies to something we cannot place — the false-clean direction.
    for (const s of ['', null, undefined, '   ', 'something-nobody-parsed']) {
      assert.equal(classifyResolution(s), 'unknown', String(s));
    }
  });

  test('packageNameOf keeps a scope', () => {
    assert.equal(packageNameOf('@babel/code-frame@^7.0.0'), '@babel/code-frame');
    assert.equal(packageNameOf('"@babel/code-frame@^7.0.0"'), '@babel/code-frame');
    assert.equal(packageNameOf('rimraf@^2.5.4'), 'rimraf');
    assert.equal(packageNameOf('closure-net@git+https://github.com/google/closure-net.git#6f48f578'), 'closure-net');
  });
});

describe('dep-provenance — yarn.lock', () => {
  // Shapes taken verbatim from firebase/firebase-js-sdk's yarn.lock.
  const YARN_V1 = `# THIS IS AN AUTOGENERATED FILE

"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.12.13":
  version "7.26.2"
  resolved "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.26.2.tgz#4b5fab97d33338eff916235055f0ebc21e573a85"
  integrity sha512-RJlIHRueQgwWitWgF8OdFYGZX328Ax5BCemNGlqHfplnRT9ESi8JkFlvaVYbS+UubVY6dpv87Fs2u5M29iNFVQ==
  dependencies:
    "@babel/helper-validator-identifier" "^7.25.9"

"closure-net@git+https://github.com/google/closure-net.git#6f48f578d3e80fe7a85e530a5d95b9351433d135":
  version "0.0.0"
  resolved "git+https://github.com/google/closure-net.git#6f48f578d3e80fe7a85e530a5d95b9351433d135"

rimraf@^2.5.4, rimraf@^2.6.3:
  version "2.7.1"
  resolved "https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz#35797f13a7fdadc566142c29d4f07ccad483e3ec"
`;

  test('the measured case: closure-net resolves from git', () => {
    const p = parseYarnLock(YARN_V1);
    assert.equal(p['closure-net'].resolution, 'git');
    assert.match(p['closure-net'].target, /^git\+https:\/\/github\.com\/google\/closure-net\.git#6f48f578/);
  });

  test('a SCOPED registry package is registry — the @ in its path is not a protocol separator', () => {
    // This regressed 436 of firebase's 1,755 packages to `unknown`: an unconditional split on the
    // last @ landed on the scope inside the tarball URL.
    const p = parseYarnLock(YARN_V1);
    assert.equal(p['@babel/code-frame'].resolution, 'registry');
  });

  test('one header can name several specifiers, and all of them get the resolution', () => {
    const p = parseYarnLock(YARN_V1);
    assert.equal(p.rimraf.resolution, 'registry');
    assert.equal(Object.keys(p).length, 3, 'three packages, however many specifiers named them');
  });

  test('a `dependencies:` block is never mistaken for a resolution', () => {
    const p = parseYarnLock(YARN_V1);
    assert.equal(p['@babel/helper-validator-identifier'], undefined);
  });

  test('yarn BERRY resolution strings', () => {
    const berry = `"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"

"thing@https://github.com/a/b.git#commit=abc":
  version: 0.0.0
  resolution: "thing@https://github.com/a/b.git#commit=abc"
`;
    const p = parseYarnLock(berry);
    assert.equal(p.lodash.resolution, 'registry');
    assert.equal(p.thing.resolution, 'git');
  });

  test('empty and malformed input yields an empty map, not a throw', () => {
    for (const t of ['', null, undefined, 'garbage\nmore garbage']) {
      assert.deepEqual(parseYarnLock(t), {});
    }
  });
});

describe('dep-provenance — package-lock.json', () => {
  test('v2/v3 packages block', () => {
    const p = parsePackageLock({ packages: {
      '': { name: 'root' },
      'node_modules/rimraf': { resolved: 'https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz' },
      'node_modules/closure-net': { resolved: 'git+https://github.com/google/closure-net.git#6f48f578' },
      'node_modules/@babel/core': { resolved: 'https://registry.npmjs.org/@babel/core/-/core-7.0.0.tgz' },
    } });
    assert.equal(p.rimraf.resolution, 'registry');
    assert.equal(p['closure-net'].resolution, 'git');
    assert.equal(p['@babel/core'].resolution, 'registry');
    assert.equal(p.root, undefined, 'the root project is not a dependency');
  });

  test('v1 dependencies block, recursively', () => {
    const p = parsePackageLock({ dependencies: {
      a: { resolved: 'https://registry.npmjs.org/a/-/a-1.0.0.tgz',
        dependencies: { b: { resolved: 'git+https://github.com/x/b.git#sha' } } },
    } });
    assert.equal(p.a.resolution, 'registry');
    assert.equal(p.b.resolution, 'git');
  });

  test('an entry with NO resolved is unknown, never registry', () => {
    const p = parsePackageLock({ packages: { 'node_modules/x': { version: '1.0.0' } } });
    assert.equal(p.x.resolution, 'unknown');
  });

  test('empty and malformed input', () => {
    for (const d of [{}, null, undefined]) assert.deepEqual(parsePackageLock(d), {});
  });
});

describe('dep-provenance — the finding is the MIGRATION, not the state', () => {
  const before = { 'closure-net': { resolution: 'registry', target: 'https://registry.npmjs.org/closure-net/-/closure-net-1.0.0.tgz' },
    rimraf: { resolution: 'registry', target: 'https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz' } };
  const after = { 'closure-net': { resolution: 'git', target: 'git+https://github.com/attacker/closure-net.git#bad' },
    rimraf: { resolution: 'registry', target: 'https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz' } };

  test('the attack this exists for: a dependency moves off the registry', () => {
    const d = diffProvenance(before, after);
    assert.equal(d.offRegistry, 1);
    assert.equal(d.moved.length, 1);
    assert.equal(d.moved[0].package, 'closure-net');
    assert.equal(d.moved[0].from, 'registry');
    assert.equal(d.moved[0].to, 'git');
    assert.match(d.moved[0].toTarget, /attacker/);
    assert.match(d.note, /moved OFF a package registry/);
  });

  test('a repo that has ALWAYS used a git dependency is not an event', () => {
    const stable = { 'closure-net': { resolution: 'git', target: 'git+https://github.com/google/closure-net.git#6f48f578' } };
    const d = diffProvenance(stable, stable);
    assert.equal(d.moved.length, 0);
    assert.equal(d.note, '', 'reporting the state would bury the event in a population');
  });

  test('an appearance or a disappearance is not a migration', () => {
    assert.equal(diffProvenance({}, after).moved.length, 0, 'a new dependency is not a move');
    assert.equal(diffProvenance(before, {}).moved.length, 0, 'a removed dependency is not a move');
  });

  test('a move to or from UNKNOWN is a parser gap, not an incident', () => {
    // Manufacturing an event out of our own blind spot is the over-reporting direction.
    assert.equal(diffProvenance(before, { 'closure-net': { resolution: 'unknown' }, rimraf: before.rimraf }).moved.length, 0);
    assert.equal(diffProvenance({ 'closure-net': { resolution: 'unknown' } }, after).moved.length, 0);
  });

  test('a move TOWARD the registry is reported, and is not offRegistry', () => {
    const d = diffProvenance(after, before);
    assert.equal(d.moved.length, 1);
    assert.equal(d.moved[0].offRegistry, false);
    assert.equal(d.offRegistry, 0);
    assert.equal(d.note, '');
  });

  test('off-registry moves sort first', () => {
    const b = { a: { resolution: 'git' }, z: { resolution: 'registry' } };
    const a2 = { a: { resolution: 'registry' }, z: { resolution: 'git' } };
    assert.equal(diffProvenance(b, a2).moved[0].package, 'z');
  });

  test('the override disables the comparison', () => {
    process.env.CW_DEP_PROVENANCE = 'off';
    const d = diffProvenance(before, after);
    assert.equal(d.enabled, false);
    assert.equal(d.moved.length, 0);
  });

  test('empty and absent inputs are tolerated', () => {
    for (const [b, a] of [[null, null], [undefined, undefined], [{}, {}]]) {
      assert.equal(diffProvenance(b, a).moved.length, 0);
    }
  });
});

describe('dep-provenance — comparing two slices, and the first one', () => {
  const inv = (packages) => ({ ran: true, packages });
  const disk = (map) => (p) => { if (!(p in map)) throw new Error('ENOENT'); return map[p]; };

  test('a migration between slices is reported', () => {
    const r = compareSlices('/prev/repo', '/cur/repo', disk({
      '/prev/repo/dep-provenance.json': inv({ x: { resolution: 'registry', target: 'https://registry.npmjs.org/x/-/x-1.0.0.tgz' } }),
      '/cur/repo/dep-provenance.json': inv({ x: { resolution: 'git', target: 'git+https://github.com/a/x.git#s' } }),
    }));
    assert.equal(r.offRegistry, 1);
    assert.equal(r.moved[0].package, 'x');
    assert.equal(r.unknown, undefined);
  });

  test('THE FIRST SLICE IS no-reference, never a clean no-migration result', () => {
    // "no migration detected" and "nothing to compare against" are the same output. They must
    // not be the same claim.
    const r = compareSlices(null, '/cur/repo', disk({ '/cur/repo/dep-provenance.json': inv({ x: { resolution: 'git' } }) }));
    assert.equal(r.unknown, true);
    assert.equal(r.unknownReason, 'no-reference');
    assert.equal(r.offRegistry, 0);
    assert.equal(r.inventoried, 1, 'it still says how much it inventoried');
  });

  test('a previous slice with no inventory for this repo is also no-reference', () => {
    const r = compareSlices('/prev/repo', '/cur/repo', disk({ '/cur/repo/dep-provenance.json': inv({ x: { resolution: 'git' } }) }));
    assert.equal(r.unknownReason, 'no-reference');
  });

  test('no inventory THIS slice is not-run — distinct from having nothing to compare', () => {
    const r = compareSlices('/prev/repo', '/cur/repo', disk({ '/prev/repo/dep-provenance.json': inv({}) }));
    assert.equal(r.unknownReason, 'not-run');
  });

  test('an inventory that failed to collect is not read as an empty one', () => {
    const r = compareSlices('/prev/repo', '/cur/repo', disk({
      '/prev/repo/dep-provenance.json': inv({ x: { resolution: 'registry' } }),
      '/cur/repo/dep-provenance.json': { ran: false, reason: 'no-subject', packages: {} },
    }));
    assert.equal(r.unknownReason, 'not-run', 'ran:false must never compare as "everything vanished"');
    assert.equal(r.moved.length, 0);
  });

  test('a stable repo compares clean, and says how much it looked at', () => {
    const same = inv({ x: { resolution: 'git' }, y: { resolution: 'registry' } });
    const r = compareSlices('/prev/repo', '/cur/repo', disk({
      '/prev/repo/dep-provenance.json': same, '/cur/repo/dep-provenance.json': same,
    }));
    assert.equal(r.unknown, undefined);
    assert.equal(r.moved.length, 0);
    assert.equal(r.inventoried, 2);
  });
});

// ── same-class target drift (2026-08-27) ─────────────────────────────────────────────────────────
// The class comparison alone was blind to the exact attack the module header describes: a git pin
// re-pointed at another org is git before and git after. These pin the drift branch.
describe('target drift within one resolution class', () => {
  test('a git pin re-pointed at another org on the SAME host is the event', () => {
    const d = diffProvenance(
      { x: { resolution: 'git', target: 'git+https://github.com/google/closure-net.git#abc' } },
      { x: { resolution: 'git', target: 'git+https://github.com/evil/closure-net.git#abc' } });
    assert.equal(d.targetDrift, 1);
    assert.equal(d.moved[0].kind, 'target-drift');
    assert.equal(d.moved[0].fromIdentity, 'github.com/google');
    assert.equal(d.moved[0].toIdentity, 'github.com/evil');
    assert.equal(d.moved[0].offRegistry, false, 'not an off-registry move — its own kind');
  });

  test('a registry version bump on the same host is NOT an event', () => {
    const d = diffProvenance(
      { x: { resolution: 'registry', target: 'https://registry.npmjs.org/x/-/x-1.0.0.tgz' } },
      { x: { resolution: 'registry', target: 'https://registry.npmjs.org/x/-/x-2.0.0.tgz' } });
    assert.equal(d.moved.length, 0, 'same host, different path — ordinary');
  });

  test('a registry HOST change is an event — the dependency-confusion shape', () => {
    const d = diffProvenance(
      { x: { resolution: 'registry', target: 'https://registry.npmjs.org/x/-/x-1.0.0.tgz' } },
      { x: { resolution: 'registry', target: 'https://registry.npmmirror.com/x/-/x-1.0.0.tgz' } });
    assert.equal(d.targetDrift, 1);
    assert.equal(d.moved[0].fromIdentity, 'registry.npmjs.org');
  });

  test('one uncomparable side is a vintage mismatch, never an event', () => {
    const d = diffProvenance(
      { x: { resolution: 'registry', target: 'npm:1.2.3' } },  // berry writes no host
      { x: { resolution: 'registry', target: 'https://registry.npmjs.org/x/-/x-1.2.3.tgz' } });
    assert.equal(d.moved.length, 0, 'our blind spot is not an incident');
  });

  test('file resolutions never drift — local paths name no source anyone serves', () => {
    const d = diffProvenance(
      { x: { resolution: 'file', target: 'file:../a' } },
      { x: { resolution: 'file', target: 'file:../b' } });
    assert.equal(d.moved.length, 0);
  });

  test('scp-style git remotes compare by host+org like URL remotes', () => {
    assert.equal(targetIdentity('git', 'git@github.com:google/closure-net.git'), 'github.com/google');
    assert.equal(targetIdentity('git', 'git+ssh://git@github.com/google/closure-net.git'), 'github.com/google');
    assert.equal(targetIdentity('registry', 'npm:1.2.3'), null, 'no host, no identity, no claim');
  });

  test('a class move still reports as before, now carrying its kind', () => {
    const d = diffProvenance(
      { x: { resolution: 'registry', target: 'https://registry.npmjs.org/x/-/x-1.0.0.tgz' } },
      { x: { resolution: 'git', target: 'git+https://github.com/evil/x.git#abc' } });
    assert.equal(d.moved[0].kind, 'resolution');
    assert.equal(d.moved[0].offRegistry, true);
    assert.equal(d.offRegistry, 1);
  });
});
