// node --test monitor/test/  — bin/deploy.mjs --write CONTAINMENT: every proven bypass replayed
// (case-folded path, symlinked parent, symlinked target file). Every case runs under a throwaway
// $HOME so the negative is safe to FAIL; the last test asserts the real ~/.cloudflared has no litter.

import { describe, test, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { homedir, tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const CW = resolve(HERE, '../..');
const DEPLOY = join(CW, 'bin', 'deploy.mjs');

// one public area suffices; the deliberately not-listening origin only WARNs
const REGISTRY = {
  reportsRoot: 'reports',
  areas: [{
    slug: 'app', label: 'App',
    deploy: { hostnames: ['app.example.com'], service: 'https://127.0.0.1:59443', public: true, requiresAuth: false },
  }],
  projects: [{ name: 'app-core', area: 'app', path: '~/x/app', manifest: 'm' }],
};

const CANARY = 'tunnel: real-and-live\ncredentials-file: /nope.json\ningress:\n  - service: http_status:404\n';
const roots = [];
// throwaway HOME with a real .cloudflared carrying a canary config; /var/folders is itself a
// symlink, so every path here exercises realpath resolution for free
function fakeHome({ launchAgents = true } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'cw-contain-'));
  roots.push(root);
  const home = join(root, 'home');
  mkdirSync(join(home, '.cloudflared'), { recursive: true });
  mkdirSync(join(home, 'out'), { recursive: true });
  if (launchAgents) mkdirSync(join(home, 'Library', 'LaunchAgents'), { recursive: true });
  writeFileSync(join(home, '.cloudflared', 'config.yml'), CANARY);
  writeFileSync(join(root, 'reg.json'), JSON.stringify(REGISTRY));
  return { root, home, registry: join(root, 'reg.json') };
}
after(() => { for (const r of roots) rmSync(r, { recursive: true, force: true }); });

// os.homedir() reads $HOME on POSIX, so FORBIDDEN's home-relative entries resolve inside the fixture
function write(env, target) {
  const r = spawnSync(process.execPath, [DEPLOY, '--registry', env.registry, '--write', target],
    // BOTH, because os.homedir() reads a different variable per platform: $HOME on POSIX and
    // %USERPROFILE% on Windows. Setting only HOME left homedir() pointing at the REAL home here, so
    // FORBIDDEN's home-relative entries resolved outside the fixture, every --write target inside it
    // was legitimately allowed, and eight containment tests read "expected exit 2, got 0". They were
    // not detecting a hole in the guard — they were never relocating the home the guard protects.
    // Worth being precise about, because a containment test that fails and a containment guard that
    // fails open look identical from the failure line alone.
    { cwd: CW, encoding: 'utf8', env: { ...process.env, HOME: env.home, USERPROFILE: env.home }, stdio: ['ignore', 'pipe', 'pipe'] });
  return { code: r.status ?? -1, stdout: String(r.stdout || ''), stderr: String(r.stderr || '') };
}
// check the listing too — the bypasses created a new file, they did not overwrite config.yml
function cloudflaredUntouched(env, what) {
  assert.deepEqual(readdirSync(join(env.home, '.cloudflared')).sort(), ['config.yml'],
    `${what}: a file landed in the daemon's config directory`);
  assert.equal(readFileSync(join(env.home, '.cloudflared', 'config.yml'), 'utf8'), CANARY,
    `${what}: the live config was modified`);
}
const refused = (r, what) => {
  assert.equal(r.code, 2, `${what}: expected exit 2, got ${r.code}\nstdout:${r.stdout}\nstderr:${r.stderr}`);
  assert.match(r.stderr, /REFUSED/, `${what}: the refusal must be loud`);
  assert.ok(!/^wrote /m.test(r.stdout), `${what}: it claimed to have written something`);
};

describe('bin/deploy.mjs --write — the containment guard, under a throwaway HOME', () => {
  test('CONTROL: a plain operator-named path still works, so the refusals below are not vacuous', () => {
    const env = fakeHome();
    const target = join(env.home, 'out', 'fragment.yml');
    const r = write(env, target);
    assert.equal(r.code, 0, `a legitimate --write must succeed:\n${r.stderr}`);
    assert.ok(existsSync(target), 'the fragment must actually be written');
    assert.match(readFileSync(target, 'utf8'), /^# GENERATED by bin\/deploy\.mjs/);
    assert.match(r.stdout, /^wrote /m);
    cloudflaredUntouched(env, 'control');
  });

  test('the direct write into ~/.cloudflared/ is refused (the case the guard was built for)', () => {
    const env = fakeHome();
    const r = write(env, join(env.home, '.cloudflared', 'direct.yml'));
    refused(r, 'direct');
    assert.match(r.stderr, /APPLYING, which stays human/);
    cloudflaredUntouched(env, 'direct');
  });

  test('(A) CASE ALONE does not defeat it: --write ~/.CloudFlared/pwned.yml', function (t) {
    const env = fakeHome();
    // meaningful only where the volume folds case
    if (!existsSync(join(env.home, '.CloudFlared'))) return t.skip('case-sensitive volume: .CloudFlared does not resolve');
    const r = write(env, join(env.home, '.CloudFlared', 'pwned.yml'));
    refused(r, 'case');
    cloudflaredUntouched(env, 'case');
  });

  test('(B) a SYMLINKED PARENT does not defeat it: ln -s ~/.cloudflared link; --write link/x.yml', () => {
    const env = fakeHome();
    symlinkSync(join(env.home, '.cloudflared'), join(env.home, 'link'));
    const r = write(env, join(env.home, 'link', 'pwned2.yml'));
    refused(r, 'symlinked parent');
    assert.match(r.stderr, /resolves inside/);
    cloudflaredUntouched(env, 'symlinked parent');
  });

  test('(C) a SYMLINKED TARGET FILE under an innocent parent does not defeat it', () => {
    // the link dangles — writeFileSync would have created the far end inside .cloudflared/
    const env = fakeHome();
    mkdirSync(join(env.home, 'innocent'));
    symlinkSync(join(env.home, '.cloudflared', 'pwned3.yml'), join(env.home, 'innocent', 'frag.yml'));
    const r = write(env, join(env.home, 'innocent', 'frag.yml'));
    refused(r, 'symlinked target');
    assert.match(r.stderr, /is a symlink/);
    cloudflaredUntouched(env, 'symlinked target');
  });

  test('a symlinked target pointing somewhere HARMLESS is refused too — the rule is simple on purpose', () => {
    const env = fakeHome();
    mkdirSync(join(env.home, 'innocent'));
    symlinkSync(join(env.home, 'out', 'real.yml'), join(env.home, 'innocent', 'frag.yml'));
    const r = write(env, join(env.home, 'innocent', 'frag.yml'));
    refused(r, 'harmless symlink');
    assert.equal(existsSync(join(env.home, 'out', 'real.yml')), false, 'nothing may be written through a link');
  });

  test('--write ~/.cloudflared (the DIRECTORY itself) is refused, not an EISDIR crash', () => {
    const env = fakeHome();
    const r = write(env, join(env.home, '.cloudflared'));
    refused(r, 'the directory itself');
    assert.ok(!/EISDIR/.test(r.stderr), 'it must refuse deliberately, not die on the syscall');
    cloudflaredUntouched(env, 'the directory itself');
  });

  test('a trailing slash and a .. detour reach the same place and are refused the same way', () => {
    const env = fakeHome();
    for (const t of [join(env.home, '.cloudflared') + '/', join(env.home, 'out', '..', '.cloudflared', 'x.yml')]) {
      refused(write(env, t), `normalised path ${t}`);
    }
    cloudflaredUntouched(env, 'normalised paths');
  });
});

describe('the FORBIDDEN list — launchd is an apply surface too, and absent dirs still count', () => {
  test('~/Library/LaunchAgents is refused: writing a job launchd starts at login IS applying', () => {
    // a plist landing here is executed at next login — a broader apply than the cloudflared config
    const env = fakeHome();
    const r = write(env, join(env.home, 'Library', 'LaunchAgents', 'com.evil.plist'));
    refused(r, 'LaunchAgents');
    assert.match(r.stderr, /launchd reads the jobs it starts at login/);
    assert.deepEqual(readdirSync(join(env.home, 'Library', 'LaunchAgents')), [], 'nothing may land in LaunchAgents');
  });

  test('a forbidden directory that does NOT exist yet is enforced the moment it appears', () => {
    // a guard that skipped an unstattable entry would fail open the day the directory is created;
    // absent refuses as parent-missing, present as containment — no state in between
    const env = fakeHome({ launchAgents: false });
    const target = join(env.home, 'Library', 'LaunchAgents', 'com.evil.plist');
    mkdirSync(join(env.home, 'Library'));
    const before = write(env, target);
    refused(before, 'LaunchAgents absent');
    assert.match(before.stderr, /does not exist/);

    mkdirSync(join(env.home, 'Library', 'LaunchAgents')); // the day it appears
    const now = write(env, target);
    refused(now, 'LaunchAgents just created');
    assert.match(now.stderr, /resolves inside/);
    assert.equal(existsSync(target), false);
  });

  test('a SYMLINKED ancestor of a forbidden directory is resolved, not compared as a string', () => {
    // both sides must go through realpath — ~/Library itself is the link here
    const env = fakeHome({ launchAgents: false });
    const elsewhere = join(env.root, 'elsewhere');
    mkdirSync(join(elsewhere, 'LaunchAgents'), { recursive: true });
    symlinkSync(elsewhere, join(env.home, 'Library'));
    const r = write(env, join(env.home, 'Library', 'LaunchAgents', 'com.evil.plist'));
    refused(r, 'symlinked Library');
    assert.deepEqual(readdirSync(join(elsewhere, 'LaunchAgents')), []);
  });

  test('the list still names every apply surface — it must not silently shrink', () => {
    // system dirs cannot be exercised without mutating the real machine — membership pinned from source
    const src = readFileSync(DEPLOY, 'utf8');
    const i = src.indexOf('const FORBIDDEN = [');
    assert.ok(i > 0, 'bin/deploy.mjs must still declare a FORBIDDEN list');
    const block = src.slice(i, src.indexOf('];', i));
    for (const entry of ["join(homedir(), '.cloudflared')", "join(homedir(), 'Library', 'LaunchAgents')",
      "'/etc/cloudflared'", "'/usr/local/etc/cloudflared'", "'/opt/homebrew/etc/cloudflared'"]) {
      assert.ok(block.includes(entry), `FORBIDDEN no longer contains ${entry}`);
    }
  });

  test('THE SUITE ITSELF left no litter in the operator\'s real ~/.cloudflared', () => {
    // asserts, rather than trusts, that nothing above named the real home
    const real = join(homedir(), '.cloudflared');
    if (!existsSync(real)) return;
    const litter = readdirSync(real).filter((f) => /^(pwned|com\.evil|direct|fragment|frag|x)\b/.test(f) || /^cw-contain/.test(f));
    assert.deepEqual(litter, [], 'this suite must never write into the real ~/.cloudflared');
  });
});
