// lib/test/docsite-page-units.test.mjs — case tests for render404, renderIndex, renderShellPage.
import test from 'node:test';
import assert from 'node:assert/strict';
import { render404, renderIndex, renderShellPage, metaDescription } from '../docsite-page.mjs';

test('returns a string', () => {
  const html = render404();
  assert.equal(typeof html, 'string');
});

test('starts with doctype', () => {
  const html = render404();
  assert.ok(html.startsWith('<!doctype html>'));
});


test('contains link to index', () => {
  const html = render404();
  assert.ok(html.includes('<a href="/">The document index</a>'));
});

test('has title "Not found"', () => {
  const html = render404();
  assert.ok(html.includes('<title>Not found — commitwork docs</title>'));
});

test('is deterministic', () => {
  assert.equal(render404(), render404());
});

test('contains generated-by comment', () => {
  const html = render404();
  assert.ok(html.includes('Generated by bin/docsite-build.mjs'));
});

test('renders empty rows list with default note', () => {
  const html = renderIndex({ rows: [] });
  assert.ok(html.includes('<ul class="doclist">\n\n</ul>'));
  assert.ok(html.includes('<title>Documents — commitwork docs</title>'));
});

test('renders single published row without badge or freshness', () => {
  const html = renderIndex({ rows: [{ title: 'Guide', href: '/guide/', state: 'published', freshness: 'fresh' }] });
  assert.ok(html.includes('<li><a href="/guide/">Guide</a></li>'));
  assert.ok(!html.includes('class="badge"'));
  assert.ok(!html.includes('class="fresh'));
});

test('renders draft row with badge but no freshness when showFreshness is false', () => {
  const html = renderIndex({ rows: [{ title: 'Draft Doc', href: '/draft/', state: 'draft', freshness: 'stale' }] });
  assert.ok(html.includes('<span class="badge">draft</span>'));
  assert.ok(!html.includes('class="fresh'));
});

test('renders freshness span when showFreshness is true', () => {
  const html = renderIndex({ rows: [{ title: 'Doc', href: '/doc/', state: 'published', freshness: 'stale' }], showFreshness: true });
  assert.ok(html.includes('<span class="fresh stale">stale</span>'));
});

test('renders imported freshness as unknown class', () => {
  const html = renderIndex({ rows: [{ title: 'Imp', href: '/imp/', state: 'published', freshness: 'imported' }], showFreshness: true });
  assert.ok(html.includes('<span class="fresh unknown">imported snapshot</span>'));
});

test('renders label instead of freshness when label is present', () => {
  const html = renderIndex({ rows: [{ title: 'Doc', href: '/doc/', state: 'published', freshness: 'fresh', label: 'DRAFT' }], showFreshness: true });
  assert.ok(html.includes('<span class="fresh label">DRAFT</span>'));
  assert.ok(!html.includes('<span class="fresh fresh">'));
});

test('renders note paragraph when provided', () => {
  const html = renderIndex({ rows: [], note: 'Welcome' });
  assert.ok(html.includes('<p>Welcome</p>'));
});

test('escapes HTML in title and href', () => {
  const html = renderIndex({ rows: [{ title: '<script>', href: '/a?b="c"', state: 'published', freshness: 'fresh' }] });
  assert.ok(html.includes('&lt;script&gt;'));
  assert.ok(html.includes('href="/a?b=&quot;c&quot;"'));
});

test('renders basic shell with title and body', () => {
  const html = renderShellPage({ title: 'Test', bodyHtml: '<p>Body</p>', srcHash: 'a'.repeat(64) });
  assert.ok(html.includes('<title>Test — commitwork docs</title>'));
  assert.ok(html.includes('<h1>Test</h1>'));
  assert.ok(html.includes('<p>Body</p>'));
});

test('includes src-sha256 in body data attribute', () => {
  const hash = 'b'.repeat(64);
  const html = renderShellPage({ title: 'T', bodyHtml: '', srcHash: hash });
  assert.ok(html.includes(`data-src-sha256="${hash}"`));
});

test('includes truncated hash in comment header', () => {
  const hash = 'c'.repeat(64);
  const html = renderShellPage({ title: 'T', bodyHtml: '', srcHash: hash });
  assert.ok(html.includes(`src-sha256:${hash.slice(0, 12)}`));
});

test('includes truncated hash in footer', () => {
  const hash = 'd'.repeat(64);
  const html = renderShellPage({ title: 'T', bodyHtml: '', srcHash: hash });
  assert.ok(html.includes(`src ${hash.slice(0, 12)}`));
});

test('renders nav with aria-current for matching slug', () => {
  const html = renderShellPage({
    title: 'T', bodyHtml: '', srcHash: 'e'.repeat(64),
    nav: [{ href: '/a', title: 'A', slug: 'a' }, { href: '/b', title: 'B', slug: 'b' }],
    currentSlug: 'a'
  });
  assert.ok(html.includes('aria-current="page"'));
  assert.ok(html.includes('href="/a"'));
});

test('renders empty nav when nav array is empty', () => {
  const html = renderShellPage({ title: 'T', bodyHtml: '', srcHash: 'f'.repeat(64), nav: [] });
  assert.ok(!html.includes('<nav'));
});

test('includes badge in h1', () => {
  const html = renderShellPage({ title: 'T', bodyHtml: '', srcHash: 'g'.repeat(64), badge: '<span class="badge">draft</span>' });
  assert.ok(html.includes('<h1>T<span class="badge">draft</span></h1>'));
});

test('includes extraHead after style tag', () => {
  const html = renderShellPage({ title: 'T', bodyHtml: '', srcHash: 'h'.repeat(64), extraHead: '<link rel="stylesheet" href="x.css">' });
  assert.ok(html.includes('</style><link rel="stylesheet" href="x.css">'));
});

test('renderShellPage: a docsite page is wrapped in Cloudflare email_off markers, and a page with no site links is not', () => {
  const site = renderShellPage({ title: 'T', bodyHtml: '<p><a href="mailto:a@example.com">a</a></p>', srcHash: 'c'.repeat(64), siteLinks: [{ href: '/privacy/', text: 'Privacy' }] });
  const on = site.indexOf('<!--email_off-->');
  assert.ok(on > site.indexOf('<body') && on < site.indexOf('mailto:'), 'the opening marker precedes the first mailto inside <body>');
  assert.ok(site.indexOf('<!--/email_off-->') > site.lastIndexOf('</footer>'), 'the closing marker follows the footer');
  const other = renderShellPage({ title: 'T', bodyHtml: '', srcHash: 'c'.repeat(64) });
  assert.doesNotMatch(other, /email_off/, 'callers that pass no siteLinks stay byte-identical');
});

test('metaDescription removes a comment that one stripping pass would leave behind', () => {
  assert.equal(metaDescription('<!-<!-- x -->- private note -->\n\nPublic paragraph.'), 'Public paragraph.');
});
