#!/usr/bin/env node
// cra/pack.mjs — assemble the CRA Annex I Part II vulnerability-handling documentation
// pack for a product, generated from the LIVE configuration (not hand-written claims):
// the check catalogue comes from manifests/security-baseline.json, the cadence from the
// launchd schedules, the lifecycle/evidence rules from the monitor's actual gating, and
// the remediation log from the evidence-tiered ledger.
//
//   reports/cra/pack/<productId>/
//     index.md                   Annex I Part II (1)–(8) crosswalk → artifact + status
//     vulnerability-handling.md  the process, as configured (tools, cadence, gating)
//     cvd-policy.md              coordinated vulnerability disclosure policy (template)
//     remediation-log.md         verified fixes for the product's repos (strong/medium)
//     advisories.md              fixed-vulnerability disclosure log (stub to maintain)
//
//   node cra/pack.mjs [--product <id>]
//
// Zero deps.

import { isMainModule } from '../lib/is-main.mjs';
import { join, dirname } from 'node:path';
import { existsSync } from 'node:fs';
import {
  loadJSON, writeTextAtomic, resolvePaths, loadProducts, nowISO,
  resolveEvidenceForRepos, manifestIdsForRepos,
} from './lib.mjs';

function generatedBanner(at) {
  return `_Generated by commitwork cra/pack.mjs at ${at} from live configuration — regenerate, don't hand-edit. Items marked **[HUMAN]** need input the tooling cannot know._\n`;
}

// R22 fix 3: resolve the check catalogue PER PRODUCT from the manifest(s) its own repos
// actually run (monitor/projects.json projects[].manifest, possibly an array — client-a runs
// three, internal-b-dev runs its own 'internal-b-dev' manifest), unioned and deduped by check id —
// instead of always documenting manifests/security-baseline.json regardless of which
// manifest(s) a product's repos are really scanned against. CW_BASELINE_MANIFEST, when set,
// overrides this entirely with one fixed file — the deterministic single-manifest setup tests
// use, and a general escape hatch for a product whose manifest resolution needs pinning.
function baselineForProduct(product, paths) {
  if (process.env.CW_BASELINE_MANIFEST) return loadJSON(paths.baselineManifest, { checks: [] });
  const { ids } = manifestIdsForRepos(product.repos || [], paths);
  const manifestsDir = dirname(paths.baselineManifest);
  const seen = new Set();
  const checks = [];
  for (const id of ids) {
    const doc = loadJSON(join(manifestsDir, `${id}.json`), null);
    for (const c of doc?.checks || []) if (c?.id && !seen.has(c.id)) { seen.add(c.id); checks.push(c); }
  }
  return { checks, manifestIds: ids };
}

function mttr(entries) {
  // born/resolved slice stamps are sweep ids (sweep-YYYYMMDDHHmmss) — parse best-effort
  const ts = (s) => { const m = /(\d{14})/.exec(s || ''); if (!m) return null; const x = m[1]; return Date.UTC(+x.slice(0, 4), +x.slice(4, 6) - 1, +x.slice(6, 8), +x.slice(8, 10), +x.slice(10, 12), +x.slice(12, 14)); };
  const days = entries.map((e) => { const a = ts(e.bornSlice), b = ts(e.resolvedSlice); return a && b ? (b - a) / 86400000 : null; }).filter((d) => d != null && d >= 0);
  if (!days.length) return null;
  return { n: days.length, meanDays: +(days.reduce((s, d) => s + d, 0) / days.length).toFixed(1), maxDays: +Math.max(...days).toFixed(1) };
}

export function buildPack(product, manufacturer, baseline, ledgerEntries, paths, at) {
  const repoSet = new Set(product.repos || []);
  const productLedger = ledgerEntries.filter((e) => repoSet.has(e.repo));
  const verified = productLedger.filter((e) => ['strong', 'medium'].includes(e.evidence?.tier));
  const stats = mttr(verified);
  const checks = (baseline.checks || []).map((c) => `| ${c.id} | ${c.description || ''} | ${(c.groups || []).join(', ')} |`);
  // R22 fix 3: named here, not hardcoded as "the commitwork security baseline" — a product's
  // repos may run a different manifest (or several) entirely (e.g. internal-b-dev's own manifest),
  // and the table below is only honest if the prose above it names what actually produced it.
  const manifestLabel = Array.isArray(baseline.manifestIds) && baseline.manifestIds.length ? baseline.manifestIds.join(', ') : 'security-baseline';

  const vulnHandling = `# Vulnerability handling — ${product.name} ${product.version}

${generatedBanner(at)}
## Continuous identification (Annex I Part II (1), (3))

Every repo shipping in this product is scanned against **${(baseline.checks || []).length} check(s)**
drawn from manifest(s) **${manifestLabel}** — the checks this product's repos actually run, listed
below (not a fixed catalogue asserted regardless of which manifest applies):

| Check | What it does | Groups |
|---|---|---|
${checks.join('\n')}

**Cadence:** one sweep agent per declared area (launchd \`com.portll.commitwork-monitor-<area>\`,
nightly from 02:30 and staggered, or weekly where the area declares that cadence) plus a 30-minute
exploited-vulnerability watch (launchd \`com.portll.commitwork-cra-watch\`) joining open findings
against the CISA KEV catalog and EPSS. Both are generated per machine by
\`monitor/install-agents.mjs\`.

**Provenance gating (why a green cell is trustworthy):** a finding may only transition to
resolved if its repo was in the sweep's scope AND the reporting tool provably ran
(checks-status.json + artifact presence). A scoped or failed sweep carries findings
forward as \`unknown-not-scanned\` — explicit uncertainty, and coverage voids are listed
per sweep, never silently dropped.

## Remediation without delay (Annex I Part II (2))

Findings are ranked by real-world exploitation (KEV membership, EPSS) rather than raw
count. Fixes are recorded in an evidence-tiered remediation ledger:
**strong** = the dependency lockfile provably changed between the two slices' git
anchors; **medium** = the finding cleared while the tool ran and a fix version was
known; **weak** = merely absent — logged as *unconfirmed* and never counted as cleaned.
${stats ? `Verified fixes for this product to date: **${stats.n}** (mean time-to-remediate ${stats.meanDays} days, max ${stats.maxDays}).` : 'No verified fixes recorded for this product yet.'}

## Components documented (Annex I Part II (1))

Product SBOM (CycloneDX, top-level and transitive components, vendored fixtures
excluded): \`reports/cra/sbom/${product.id}-${product.version}.cdx.json\` — regenerate per
release with \`node cra/sbom.mjs --product ${product.id}\`. Machine-readable vulnerability
status ships alongside in all three VEX formats, generated from one statement set so they
cannot disagree: \`reports/cra/vex/${product.id}.vex.cdx.json\` (CycloneDX),
\`.vex.csaf.json\` (CSAF 2.0 — the format the SRP is expected to align with) and
\`.openvex.json\` (OpenVEX).

## Reporting actively exploited vulnerabilities (Art. 14)

The 30-minute watch opens a hash-chained case the moment an open finding in this
product is KEV-listed or crosses the EPSS threshold, starts the 24h/72h/14-day clocks,
and drafts the three notifications (\`reports/cra/cases/<caseId>/\`). Submission itself
is a human act via the ENISA single reporting platform.

## Security updates (Annex I Part II (7), (8)) **[HUMAN]**

TODO: document the mechanism by which security updates reach users (channel, signing,
default-on auto-update or notification), and that they are distributed without delay
and free of charge for the support period (until ${product.supportEndsAt || 'TODO'}).
`;

  const cvd = `# Coordinated vulnerability disclosure policy — ${product.name}

${generatedBanner(at)}
**[HUMAN]** Review, adapt, publish (e.g. at ${product.cvdPolicyUrl || 'TODO url'} and in a security.txt).

## Reporting a vulnerability

Report suspected vulnerabilities in ${product.name} to **${manufacturer.contact || 'TODO contact'}**.
We accept reports for the current release (${product.version}) and all versions in support.
Voluntary reporting can be made anonymously. Include, where possible: affected
version(s), reproduction steps, impact, any proof of concept.

## What we commit to

- Acknowledge receipt within **48 hours** [HUMAN: confirm]
- Provide an initial assessment within **5 business days** [HUMAN: confirm]
- Keep the reporter informed of remediation progress
- Credit reporters who wish to be credited once a fix ships
- Not pursue legal action for good-faith research within this policy's scope

## Disclosure

We follow coordinated disclosure: we ask reporters to allow up to **90 days**
[HUMAN: confirm] before public disclosure while a fix is developed, tested and
distributed. Fixed vulnerabilities are published at ${product.advisoriesUrl || 'TODO advisories url'}
(see advisories.md) including the affected versions, impact, and the fixed version.
`;

  const remLog = `# Verified remediation log — ${product.name}

${generatedBanner(at)}
Entries are the evidence-tiered ledger's strong/medium records for this product's repos
(weak/unconfirmed are excluded by design — absence of a finding is not proof of a fix).

| Vulnerability | Repo | Package | From → To | Evidence | Resolved slice |
|---|---|---|---|---|---|
${verified.length ? verified.map((e) => `| ${e.vulnId} | ${e.repo} | ${e.package || ''} | ${e.fromVersion || '?'} → ${e.toVersion || '?'} | ${e.evidence.tier} | ${e.resolvedSlice} |`).join('\n') : '| _none yet_ | | | | | |'}

${stats ? `**${stats.n} verified fixes · mean TTR ${stats.meanDays}d · max ${stats.maxDays}d**` : ''}
Full ledger (all tiers, including unconfirmed): \`${paths.ledger}\`
`;

  const advisories = `# Security advisories — ${product.name}

${generatedBanner(at)}
**[HUMAN]** Annex I Part II (4) requires publishing information about FIXED
vulnerabilities once a security update is available: description, affected versions,
impact, severity, and how to remediate. Append one entry per advisory here (or keep
this as the index into ${product.advisoriesUrl || 'your advisories page'}).

_No advisories published yet._
`;

  const rows = [
    ['(1) Identify & document vulnerabilities and components (SBOM)', `vulnerability-handling.md · sbom/${product.id}-${product.version}.cdx.json · vex/${product.id}.{vex.cdx,vex.csaf,openvex}.json`, existsSync(join(paths.out, 'sbom', `${product.id}-${product.version}.cdx.json`)) ? 'generated' : 'run cra/sbom.mjs'],
    ['(2) Address & remediate without delay', 'remediation-log.md (evidence-tiered ledger)', verified.length ? 'evidence present' : 'no verified fixes yet'],
    ['(3) Effective & regular tests and reviews', 'vulnerability-handling.md (baseline catalogue, cadence, provenance gating)', 'generated'],
    ['(4) Publish information about fixed vulnerabilities', 'advisories.md', '[HUMAN] maintain'],
    ['(5) Coordinated vulnerability disclosure policy', 'cvd-policy.md', '[HUMAN] review & publish'],
    ['(6) Measures to facilitate vulnerability reports', `cvd-policy.md (contact: ${manufacturer.contact || 'TODO'})`, '[HUMAN] confirm mailbox + security.txt'],
    ['(7) Secure distribution of updates', 'vulnerability-handling.md §Security updates', '[HUMAN] document mechanism'],
    ['(8) Free, timely security updates + advisories', 'vulnerability-handling.md §Security updates · advisories.md', '[HUMAN] document policy'],
  ];
  const index = `# CRA Annex I Part II crosswalk — ${product.name} ${product.version}

${generatedBanner(at)}
Reporting obligations (Art. 14) start **11 September 2026**; full CRA application
11 December 2027. This pack maps each vulnerability-handling requirement to its
artifact. Anything marked **[HUMAN]** is a statement the tooling cannot truthfully
generate — a person must supply it.

| Annex I Part II requirement | Artifact | Status |
|---|---|---|
${rows.map((r) => `| ${r[0]} | ${r[1]} | ${r[2]} |`).join('\n')}

Manufacturer: ${manufacturer.name || 'TODO'} · contact ${manufacturer.contact || 'TODO'} ·
EU market: ${product.market?.eu ? 'YES' : 'no (flip market.eu in the product registry when placed on the EU market)'} ·
category: ${product.market?.category || 'default'}
`;

  return { 'index.md': index, 'vulnerability-handling.md': vulnHandling, 'cvd-policy.md': cvd, 'remediation-log.md': remLog, 'advisories.md': advisories };
}

// ── CLI ──────────────────────────────────────────────────────────────────────
if (isMainModule(import.meta.url)) {
  const argv = process.argv.slice(2);
  const only = argv.includes('--product') ? argv[argv.indexOf('--product') + 1] : null;
  const paths = resolvePaths();
  const at = nowISO();
  const { products, manufacturer } = loadProducts(paths.products);
  for (const product of products) {
    if (only && product.id !== only) continue;
    // R22 fix 1: this product's own repos, merged across whichever declared area(s) they
    // actually resolve to — not the single global ledger, which only ever held the AMBIENT
    // area's evidence (and today, on this checkout, no product's repos are IN that area's
    // ledger at all: reports/client-a-monorepo/remediation-ledger.json does not exist).
    const { ledgerEntries } = resolveEvidenceForRepos(product.repos || [], paths);
    const baseline = baselineForProduct(product, paths);
    const files = buildPack(product, manufacturer, baseline, ledgerEntries, paths, at);
    const dir = join(paths.out, 'pack', product.id);
    for (const [name, text] of Object.entries(files)) writeTextAtomic(join(dir, name), text);
    console.log(`  ✓ ${product.id}: pack → ${dir} (${baseline.checks.length} check(s) from manifest(s): ${(baseline.manifestIds || ['security-baseline']).join(', ')}; ${ledgerEntries.length} ledger entr${ledgerEntries.length === 1 ? 'y' : 'ies'})`);
  }
}
